---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:latest
  commands:
  - go test ./...
  - go build ./...

- name: docker
  image: plugins/docker
  settings:
    repo: jonnrb/vanityserver
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

...
